### ISSUE TITLE
Remove unneeded parentheses in for loop

### ISSUE THREAD

**Issue by knocte** [nblockchain/fantomless#5]
```
let private GrabTheFirstStringBeforeTheFirstColon (lines: seq<string>) =
    seq {
        for line in (lines) do
            yield (line.Split([| ":" |], StringSplitOptions.RemoveEmptyEntries)).[0]
    }
```

should get the parens in `(lines)` removed.

**Comment by knocte** [comment]
@janus but this should not change:

```
let GrabTheFirstStringBeforeTheFirstColon () =
    seq {
        for line in (foo ()) do
            yield line
    }
```

**Comment by janus** [comment]
> @janus but this should not change:
> 
> ```
> let GrabTheFirstStringBeforeTheFirstColon () =
>     seq {
>         for line in (foo ()) do
>             yield line
>     }
> ```

Alright.

**Comment by knocte** [comment]
Fixed in https://github.com/nblockchain/fantomless/commit/e28dcb9845b428bf391c9ffd1ec49d18168d55bd
